# Путь после URL, например, /blog/
baseurl: ""
# Домен
url: "0.0.0.0"
# Папка выхода генератора
destination: ../dist

collections:
  generated:
    output: true
#    permalink: /sections/:path/
#    permalink: /sections/:path/

# BUILD SETTINGS
markdown: kramdown
