version: "3.7"

services:
  jekyll:
    image: jekyll/minimal:latest
    container_name: docs
    working_dir: /home/src
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/home
